version: "3.3"

services:
  minio:
    image: minio/minio:latest
    env_file: .env
    ports:
      - 10.10.0.3:9001:9001
    restart: always
    volumes:
      - /mnt/storage:/data
    command:
      - server
      - /data
      - --json
      - --console-address
      - ":9001"